# Configuration file for TravisCI
os: linux
dist: xenial
language: python
python: "3.6"
notifications:
  email: false

# Only build pushes from the master branch. PRs are always built.
branches:
  only:
    - master

env:
  global:
    # Doctr deploy key
    - secure: "JJyBFbcbWmtMDhq4F452/34dYOIgQBQQnB9/52cSMybJvJTq7Olsxzyg5Nzn+x+7vVgZk70gLF2eyKh09r6gsHuL17Qu1P4Nn5Y1UwLmJqY33ARvkhwybG4GH5DZDQcZcDH8X2u+/9kyV43pFbvgsIf41Z6ZxYRux1meHkSYFCOhmJPoBUjmauCUS7BIA/VErA1nS8XAaCZ+htd8ZWvGlWgXQilr+afQ/4vxkuiD0MUAY0CTqFJVmyU965Q33k7hImd2+vpERXOSGb6kq6KbevcOlxicUhE8ea22a+cQDL/znm7V4rO+XPdUn49dDSG/Ptu1aj2Z5J4L+uoYt40QzcEl+Jp7Zzvsn4nkScDRQYpiTjZ/3uOHZmPg2OudIWpsuMt1gboYP9IJfyg1Rq4pLoQRHXaYxUo+pZemP42xfhjS44lp4R6lZ+pYtY8VMbKYu+V8ZrNT4flPhXSTn7hIPQ8dj4DC/1pngUcMDnH20NSe9YcY7crLIh8KB3rbg+ShX6Nqcf0UxCcdPrpSJp7E0/DCMEMSqKUJ4oEm5Ypta7MWNXixpitTq06WwdPBK7NO/hYD88TdP4R/KAdtCpWY8rRS9KazcdPCHYJcYcq2MtdKrQdSSnWC76YQqS9q0s77VnS8z3v6DoYxSCusdWl9a+E7tdEjyzIjMR3ceiHk8tg="


# Setup the build environment
install:
  # Install the requirements
  - pip install -r requirements.txt

script:
  # Build the website HTML
  - make

#deploy:
  ## Push the built HMTL to Github pages
  #- provider: script
    #script: doctr deploy . --built-docs _build --key-path .github_deploy_key.enc --deploy-repo compgeolab/compgeolab.github.io
    #skip_cleanup: true
    #on:
      #branch: master
